### ISSUE TITLE
Flask app

### ISSUE THREAD

**Issue by wwenash** [elu267/Final_Project#1]
who want to do that

**Comment by SpacePatroller** [comment]
Flask app up and running 100% using pre trained model. Will need to set app to use final model from whoever builds the best model. 


Folder Structure

<img width="228" alt="Screen Shot 2019-03-22 at 9 45 40 PM" src="https://user-images.githubusercontent.com/41847648/54860721-1d5ae600-4cec-11e9-9cf1-4fd677b027f1.png">
