### ISSUE TITLE
Create Risk Scale for 7 conditions

### ISSUE THREAD

**Issue by OuterHome** [elu267/Final_Project#11]

**Comment by Amanser** [comment]
**Melanocytic nevi:** Low severity
-"...these lesions are benign neoplasms with no potential for malignant behavior, unless evolution of melanoma occurs."
https://emedicine.medscape.com/article/1058445-overview

**Melanoma:** High severity
https://emedicine.medscape.com/article/1295718-overview

**Benign keratosis-like lesions:** Low-Medium severity
"...keratoses are benign, but secondary tumors and Bowen disease (squamous cell carcinoma in situ) or malignant melanoma may occasionally arise within the lesion."
https://emedicine.medscape.com/article/1059477-overview

**Basal Cell Carcinoma**: High severity
"The prognosis for patients with BCC is excellent, but if the disease is allowed to progress, it can cause significant morbidity."
https://emedicine.medscape.com/article/276624-overview

**Actinic keratoses:** Medium Severity
"...a UV light–induced lesion of the skin that may progress to invasive squamous cell carcinoma. It is by far the most common lesion with malignant potential"
https://emedicine.medscape.com/article/1099775-overview

**Dermatofibroma:** Low-Medium Severity
"dermatofibromas are considered benign lesions, and the prognosis for patients with this condition is excellent. However, discomfort from pain or itching may be significant"
https://emedicine.medscape.com/article/1056742-overview

**Vascular lesions** TBD
-This category is very broad so I need to read more about the data set label.

**Comment by OuterHome** [comment]
Moving risk scale to binary display (for consumer user), although probably maintaining the classification probabilities as a technical demonstration on the web app
