### ISSUE TITLE
Model Improvements

### ISSUE THREAD

**Issue by elu267** [elu267/Final_Project#3]
1. Optimizer
2. # of layers
3. Train longer
4. Artificial Image Augmentation

**Comment by Amanser** [comment]
Updated the optimizer to SGD (from Adam) with a LR of 0.0001, momentum=1e-6, decay=0.9, and nesterov=True. These settings were used in another lesion detection data set. By epoch 15, the acc and val_acc were in the 0.15-0,20 range, so I stopped the training.
