### ISSUE TITLE
Build Heroku

### ISSUE THREAD

**Issue by OuterHome** [elu267/Final_Project#6]

**Comment by SpacePatroller** [comment]
Base Heroku Procfile and requirements.txt set up. 

https://lesionlegion.herokuapp.com/

Should be able to continually push updates to Heroku with ease as long as there are no major changes to dependencies. 

<img width="476" alt="Screen Shot 2019-03-22 at 9 50 35 PM" src="https://user-images.githubusercontent.com/41847648/54860747-93f7e380-4cec-11e9-9010-eaeaf9c6b7cf.png">
<img width="495" alt="Screen Shot 2019-03-22 at 9 50 20 PM" src="https://user-images.githubusercontent.com/41847648/54860748-94907a00-4cec-11e9-9e3f-5149550d1e7a.png">
